path: "tensorflow.keras.utils.Sequence"
tf_class {
  is_instance: "<class \'tf_keras.utils.data_utils.Sequence\'>"
  is_instance: "<class \'object\'>"
  member_method {
    name: "__getitem__"
    argspec: "args=[\'self\', \'index\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__init__"
  }
  member_method {
    name: "__iter__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__len__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "on_epoch_end"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
