# Description:
#   Contains TF-Keras models to Estimator converter

# Placeholder: load unaliased py_library

package(
    # copybara:uncomment default_applicable_licenses = ["//tf_keras:license"],
    default_visibility = [
        "//tf_keras:friends",
    ],
    licenses = ["notice"],
)

py_library(
    name = "estimator",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//:expect_tensorflow_installed",
    ],
)
