path: "tensorflow.keras.utils.custom_object_scope"
tf_class {
  is_instance: "<class \'tf_keras.saving.object_registration.CustomObjectScope\'>"
  is_instance: "<class \'object\'>"
  member_method {
    name: "__enter__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__exit__"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\'], varargs=args, keywords=None, defaults=None"
  }
}
