path: "tensorflow.keras.__internal__.SparseKerasTensor"
tf_class {
  is_instance: "<class \'tf_keras.engine.keras_tensor.SparseKerasTensor\'>"
  is_instance: "<class \'tf_keras.engine.keras_tensor.KerasTensor\'>"
  is_instance: "<class \'object\'>"
  member {
    name: "dense_shape"
    mtype: "<class \'property\'>"
  }
  member {
    name: "dtype"
    mtype: "<class \'property\'>"
  }
  member {
    name: "indices"
    mtype: "<class \'property\'>"
  }
  member {
    name: "is_tensor_like"
    mtype: "<class \'property\'>"
  }
  member {
    name: "name"
    mtype: "<class \'property\'>"
  }
  member {
    name: "node"
    mtype: "<class \'property\'>"
  }
  member {
    name: "op"
    mtype: "<class \'property\'>"
  }
  member {
    name: "shape"
    mtype: "<class \'property\'>"
  }
  member {
    name: "type_spec"
    mtype: "<class \'property\'>"
  }
  member {
    name: "values"
    mtype: "<class \'property\'>"
  }
  member_method {
    name: "__abs__"
    argspec: "args=[\'x\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__add__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__and__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__array__"
    argspec: "args=[\'self\', \'dtype\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__div__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__eq__"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__floordiv__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__ge__"
    argspec: "args=[\'x\', \'y\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__getitem__"
    argspec: "args=[\'tensor\', \'slice_spec\', \'var\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__gt__"
    argspec: "args=[\'x\', \'y\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'type_spec\', \'inferred_value\', \'name\'], varargs=None, keywords=None, defaults=[\'None\', \'None\'], "
  }
  member_method {
    name: "__invert__"
    argspec: "args=[\'x\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__iter__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__le__"
    argspec: "args=[\'x\', \'y\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__len__"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__lt__"
    argspec: "args=[\'x\', \'y\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__matmul__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__mod__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__mul__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__ne__"
    argspec: "args=[\'self\', \'other\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__neg__"
    argspec: "args=[\'x\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "__or__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__pow__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__radd__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rand__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rdiv__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rfloordiv__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rmatmul__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rmod__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rmul__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__ror__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rpow__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rsub__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rtruediv__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__rxor__"
    argspec: "args=[\'y\', \'x\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__sub__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__truediv__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "__xor__"
    argspec: "args=[\'x\', \'y\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "experimental_ref"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_tensor"
    argspec: "args=[\'cls\', \'tensor\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "from_type_spec"
    argspec: "args=[\'cls\', \'type_spec\', \'name\'], varargs=None, keywords=None, defaults=[\'None\'], "
  }
  member_method {
    name: "get_shape"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "ref"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "set_shape"
    argspec: "args=[\'self\', \'shape\'], varargs=None, keywords=None, defaults=None"
  }
  member_method {
    name: "with_values"
    argspec: "args=[\'self\'], varargs=args, keywords=kwargs, defaults=None"
  }
}
